// Package env handles reading, serializing and writing dotenv files.
//
// On push, a .env file is parsed into a map and serialized to a canonical JSON
// payload (the plaintext that gets encrypted). On pull, that JSON is turned back
// into a deterministic, sorted .env file. The existing .env is always backed up
// to .env.bak before being overwritten.
package env

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/joho/godotenv"
)

// Payload is the canonical plaintext structure that gets encrypted. Versioning
// the structure lets future clients evolve the format safely.
type Payload struct {
	Version int               `json:"v"`
	Values  map[string]string `json:"values"`
}

const payloadVersion = 1

// Read parses a dotenv file into a Payload.
func Read(path string) (*Payload, error) {
	values, err := godotenv.Read(path)
	if err != nil {
		return nil, fmt.Errorf("env: cannot read %s: %w", path, err)
	}
	return &Payload{Version: payloadVersion, Values: values}, nil
}

// Marshal serializes a Payload to the canonical JSON plaintext.
func (p *Payload) Marshal() ([]byte, error) {
	if p.Version == 0 {
		p.Version = payloadVersion
	}
	data, err := json.Marshal(p)
	if err != nil {
		return nil, fmt.Errorf("env: cannot serialize payload: %w", err)
	}
	return data, nil
}

// Unmarshal parses canonical JSON plaintext back into a Payload.
func Unmarshal(data []byte) (*Payload, error) {
	var p Payload
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("env: cannot parse decrypted payload: %w", err)
	}
	if p.Values == nil {
		p.Values = map[string]string{}
	}
	return &p, nil
}

// Format renders the payload as a deterministic dotenv file body with keys
// sorted alphabetically. Values containing whitespace or special characters are
// double-quoted.
func (p *Payload) Format() string {
	keys := make([]string, 0, len(p.Values))
	for k := range p.Values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by envsync pull — do not edit credentials here by hand.\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quoteIfNeeded(p.Values[k]))
		b.WriteByte('\n')
	}
	return b.String()
}

// quoteIfNeeded wraps a value in double quotes (escaping inner quotes and
// backslashes) when it contains characters that would otherwise break parsing.
func quoteIfNeeded(v string) string {
	if v == "" {
		return ""
	}
	if strings.ContainsAny(v, " \t\n\"'#=") {
		escaped := strings.ReplaceAll(v, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		escaped = strings.ReplaceAll(escaped, "\n", `\n`)
		return `"` + escaped + `"`
	}
	return v
}

// Backup copies an existing file to <path>.bak. It is a no-op (returns "", nil)
// when the source file does not exist. Returns the backup path on success.
func Backup(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("env: cannot stat %s: %w", path, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("env: cannot read %s for backup: %w", path, err)
	}
	backupPath := path + ".bak"
	if err := os.WriteFile(backupPath, data, info.Mode().Perm()); err != nil {
		return "", fmt.Errorf("env: cannot write backup %s: %w", backupPath, err)
	}
	return backupPath, nil
}

// Write writes the formatted payload to path with 0600 permissions (secrets).
func Write(path string, p *Payload) error {
	if err := os.WriteFile(path, []byte(p.Format()), 0o600); err != nil {
		return fmt.Errorf("env: cannot write %s: %w", path, err)
	}
	return nil
}
