// Package env handles reading, serializing and writing dotenv files.
//
// On push, a .env file is parsed into a map and serialized to a canonical JSON
// payload (the plaintext that gets encrypted). On pull, that JSON is turned back
// into a deterministic, sorted .env file. The existing .env is always backed up
// to .env.bak before being overwritten.
package env

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/joho/godotenv"
)

// Payload is the canonical plaintext structure that gets encrypted. Versioning
// the structure lets future clients evolve the format safely.
type Payload struct {
	Version int               `json:"v"`
	Values  map[string]string `json:"values"`
}

const payloadVersion = 1

// Read parses a dotenv file into a Payload.
func Read(path string) (*Payload, error) {
	values, err := godotenv.Read(path)
	if err != nil {
		return nil, fmt.Errorf("env: cannot read %s: %w", path, err)
	}
	return &Payload{Version: payloadVersion, Values: values}, nil
}

// DefaultOverrideFile is the conventional name for personal local overrides
// that are merged on pull but never pushed back to the cloud.
const DefaultOverrideFile = ".env.override"

// MergeOverride layers key=value pairs from an override dotenv file on top of the
// payload, with override values winning. It is a no-op (returns 0, nil) when the
// override file does not exist. The override file is intentionally never pushed.
func (p *Payload) MergeOverride(path string) (int, error) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return 0, nil
		}
		return 0, fmt.Errorf("env: cannot stat %s: %w", path, err)
	}
	overrides, err := godotenv.Read(path)
	if err != nil {
		return 0, fmt.Errorf("env: cannot read override %s: %w", path, err)
	}
	if p.Values == nil {
		p.Values = map[string]string{}
	}
	for k, v := range overrides {
		p.Values[k] = v
	}
	return len(overrides), nil
}

// Marshal serializes a Payload to the canonical JSON plaintext.
func (p *Payload) Marshal() ([]byte, error) {
	if p.Version == 0 {
		p.Version = payloadVersion
	}
	data, err := json.Marshal(p)
	if err != nil {
		return nil, fmt.Errorf("env: cannot serialize payload: %w", err)
	}
	return data, nil
}

// Unmarshal parses canonical JSON plaintext back into a Payload.
func Unmarshal(data []byte) (*Payload, error) {
	var p Payload
	if err := json.Unmarshal(data, &p); err != nil {
		return nil, fmt.Errorf("env: cannot parse decrypted payload: %w", err)
	}
	if p.Values == nil {
		p.Values = map[string]string{}
	}
	return &p, nil
}

// Format renders the payload as a deterministic dotenv file body with keys
// sorted alphabetically. Values containing whitespace or special characters are
// double-quoted.
func (p *Payload) Format() string {
	keys := make([]string, 0, len(p.Values))
	for k := range p.Values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by envsync pull — do not edit credentials here by hand.\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quoteIfNeeded(p.Values[k]))
		b.WriteByte('\n')
	}
	return b.String()
}

// quoteIfNeeded wraps a value in double quotes (escaping inner quotes and
// backslashes) when it contains characters that would otherwise break parsing.
func quoteIfNeeded(v string) string {
	if v == "" {
		return ""
	}
	if strings.ContainsAny(v, " \t\n\"'#=") {
		escaped := strings.ReplaceAll(v, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		escaped = strings.ReplaceAll(escaped, "\n", `\n`)
		return `"` + escaped + `"`
	}
	return v
}

// DiffResult categorizes how two key/value sets differ. Keys are sorted.
type DiffResult struct {
	OnlyLeft  []string            // keys present on the left only
	OnlyRight []string            // keys present on the right only
	Changed   []string            // keys present on both but with differing values
	Same      []string            // keys present on both with identical values
	LeftVals  map[string]string   // for value display
	RightVals map[string]string   //
}

// Diff compares two key/value maps (left = e.g. local, right = e.g. remote).
func Diff(left, right map[string]string) DiffResult {
	r := DiffResult{LeftVals: left, RightVals: right}
	for k, lv := range left {
		if rv, ok := right[k]; ok {
			if lv == rv {
				r.Same = append(r.Same, k)
			} else {
				r.Changed = append(r.Changed, k)
			}
		} else {
			r.OnlyLeft = append(r.OnlyLeft, k)
		}
	}
	for k := range right {
		if _, ok := left[k]; !ok {
			r.OnlyRight = append(r.OnlyRight, k)
		}
	}
	sort.Strings(r.OnlyLeft)
	sort.Strings(r.OnlyRight)
	sort.Strings(r.Changed)
	sort.Strings(r.Same)
	return r
}

// Identical reports whether the two sides are fully equal.
func (d DiffResult) Identical() bool {
	return len(d.OnlyLeft) == 0 && len(d.OnlyRight) == 0 && len(d.Changed) == 0
}

// Backup copies an existing file to <path>.bak. It is a no-op (returns "", nil)
// when the source file does not exist. Returns the backup path on success.
func Backup(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("env: cannot stat %s: %w", path, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("env: cannot read %s for backup: %w", path, err)
	}
	backupPath := path + ".bak"
	if err := os.WriteFile(backupPath, data, info.Mode().Perm()); err != nil {
		return "", fmt.Errorf("env: cannot write backup %s: %w", backupPath, err)
	}
	return backupPath, nil
}

// Write writes the formatted payload to path with 0600 permissions (secrets).
func Write(path string, p *Payload) error {
	if err := os.WriteFile(path, []byte(p.Format()), 0o600); err != nil {
		return fmt.Errorf("env: cannot write %s: %w", path, err)
	}
	return nil
}
